apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: Deployment
    name: myapp
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-qa
  target:
    kind: Deployment
    name: myapp
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: Service
    name: myapp
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: Route
    name: myapp-route
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-qa
  target:
    kind: Namespace
    name: myapp-development
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: RoleBinding
    name: argocd-admin
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: myapp-qa
  target:
    kind: RoleBinding
    name: myapp-development
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-qa
  target:
    kind: RoleBinding
    name: myapp-development
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-qa
  target:
    kind: Deployment
    name: myapp
images:
- name: default-route-openshift-image-registry.apps.cluster-gffzv.gffzv.sandbox2394.opentlc.com/myapp-ci/myapp-runtime
  newTag: 483b-xdvsv
resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
