apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-development
  target:
    kind: Deployment
    name: myapp

images:
- name: default-route-openshift-image-registry.apps.cluster-gffzv.gffzv.sandbox2394.opentlc.com/myapp-ci/myapp-runtime
  newTag: 483b-xdvsv
- name: default-route-openshift-image-registry.apps.cluster-xljdn.xljdn.sandbox223.opentlc.com/myapp-ci/myapp-runtime
  newTag: 483b-lc7s6
resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
