apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-development
  target:
    kind: Deployment
    name: myapp

images:
- name: default-route-openshift-image-registry.apps.ocp4.mr-openshift.co.uk/myapp-ci/myapp-runtime
  newTag: bf76-qqxrq
resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
