apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-development
  target:
    kind: Deployment
    name: myapp

images:
- name: default-route-openshift-image-registry.apps.cluster-84m6f-1.sandbox851.opentlc.com/myapp-ci/myapp-runtime
  newTag: 8cff-jxhwb
- name: default-route-openshift-image-registry.apps.cluster-8sf4w-1.8sf4w-1.sandbox2785.opentlc.com/myapp-ci/myapp-runtime
  newTag: 8cff-lrxkf
resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
