apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-development
  target:
    kind: Deployment
    name: myapp

resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
images:
- name: image-registry.openshift-image-registry.svc:5000/myapp-ci/myapp-runtime
  newTag: 39db-rwv7z
