apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-development
  target:
    kind: Deployment
    name: myapp

images:
- name: default-route-openshift-image-registry.apps.cluster-lbz56.lbz56.sandbox159.opentlc.com/myapp-ci/myapp-runtime
  newTag: c1c3-rczcw
- name: default-route-openshift-image-registry.apps.cluster-w9tn8.w9tn8.sandbox1665.opentlc.com/myapp-ci/myapp-runtime
  newTag: c1c3-hdwgv
resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
